version: "3.4"

services:
    trader:
        image: trader
        environment: 
            TZ: "America/Argentina/Buenos_Aires"
            DISPLAY: $DISPLAY 
        build: 
          context: .
          dockerfile: Dockerfile
          target: trader
        extra_hosts:
          - "www.invertironline.com:54.81.69.145"
        volumes:
          - ".:/usr/src/trader"
          - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
        hostname: 'trader'

    tester:
      image: trader
      build: 
        context: .
        dockerfile: Dockerfile
        target: trader
      volumes:
        - ".:/usr/src/trader"
      hostname: 'tester'
